name: Google Drive Backup

on:
  workflow_dispatch:  # Permet également l'exécution manuelle

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup rclone
        uses: rclone/rclone-action@v2
        with:
          # Charge la configuration de rclone à partir du secret
          rclone_conf: ${{ secrets.RCLONE_CONFIG }}

      - name: Create dated folder on backup Drive
        id: create-folder
        shell: bash
        run: |
          DATE=$(date +'%Y-%m-%d')
          rclone mkdir "shared_backups:${DATE}"
          echo "::set-output name=date::${DATE}"

      - name: Sync each shared drive to backup Drive
        shell: bash
        run: |
          DATE=${{ steps.create-folder.outputs.date }}
          # Liste des noms et des ID des drives partagés
          declare -A shared_drives=(
            ["shared1"]="0AB02_pZXo1YjUk9PVA"
          )
          for drive_name in "${!shared_drives[@]}"; do
            drive_id="${shared_drives[$drive_name]}"
            echo "Syncing $drive_name (ID: $drive_id)"
            rclone sync "remote:${drive_id}" "backup_drive:${DATE}/${drive_name}" --drive-shared-with-me --create-empty-src-dirs
          done
